#!/usr/bin/env python3
"""Placement-coloured quotient, nonnegative components and energy barriers.

The experiment follows ``PLACEMENT_QUOTIENT_PREREGISTRATION.md``.  Complete
graph/energy/orbit statistics are computed for every nonempty row in
C32/C46/P49/P21/P26.  Exact Smith decompositions are computed only for the
frozen witness selection.

The lattice is deliberately the kernel on *participating* placements:

    K_part = ker_Z [U; X] restricted to placements occurring in the fiber.

The move lattice is generated by algebraic replacements that change exactly
two named pieces.  Quotient equality is compared with, but never identified
with, squarefree nonnegative graph connectivity.
"""
from __future__ import annotations

import hashlib
import heapq
import json
import platform
import time
from collections import Counter, defaultdict, deque
from itertools import combinations, product
from pathlib import Path
from typing import Callable, Iterable

from sympy import ZZ
from sympy.polys.matrices import DomainMatrix
from sympy.polys.matrices.normalforms import smith_normal_decomp

from verify_coarea_fpt import Model, Node, Shape, load_models
from verify_coarea_next import model_from_locked


HERE = Path(__file__).resolve().parent
PACKAGES = HERE.parent.parent
PROJECT = PACKAGES.parent
OUTPUT = PROJECT / "reports" / "P42_PLACEMENT_QUOTIENT_ANALYSIS.json"
PREREGISTRATION = HERE / "PLACEMENT_QUOTIENT_PREREGISTRATION.md"

EXPECTED = {
    "C32": (136, 136, 0),
    "C46": (352, 344, 8),
    "P49-base": (1344, 1208, 136),
    "P21": (1680, 672, 1008),
    "P26": (1554, 1051, 503),
}

CellMap = Callable[[int, int], tuple[int, int]]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def shape_key(shape: Shape) -> tuple[tuple[int, int], ...]:
    return tuple(sorted(shape))


def node_key(node: Node) -> tuple[tuple[tuple[int, int], ...], ...]:
    return tuple(shape_key(shape) for shape in node)


def distribution(values: Iterable[int | str]) -> dict[str, int]:
    counts = Counter(str(value) for value in values)
    return dict(sorted(counts.items(), key=lambda item: item[0]))


def adjacency(nodes: tuple[Node, ...]) -> list[set[int]]:
    """Edges join nodes differing in exactly two named placements."""
    result = [set() for _ in nodes]
    width = len(nodes[0]) if nodes else 0
    for changed in combinations(range(width), 2):
        fixed = tuple(index for index in range(width) if index not in changed)
        buckets: dict[tuple[Shape, ...], list[int]] = defaultdict(list)
        for index, node in enumerate(nodes):
            buckets[tuple(node[position] for position in fixed)].append(index)
        for bucket in buckets.values():
            for left, right in combinations(bucket, 2):
                if all(
                    nodes[left][position] != nodes[right][position]
                    for position in changed
                ):
                    result[left].add(right)
                    result[right].add(left)
    return result


def graph_components(edges: list[set[int]]) -> tuple[list[list[int]], list[int]]:
    component_by_node = [-1] * len(edges)
    components: list[list[int]] = []
    for start in range(len(edges)):
        if component_by_node[start] >= 0:
            continue
        component_id = len(components)
        component_by_node[start] = component_id
        queue = deque([start])
        values: list[int] = []
        while queue:
            current = queue.popleft()
            values.append(current)
            for neighbour in edges[current]:
                if component_by_node[neighbour] < 0:
                    component_by_node[neighbour] = component_id
                    queue.append(neighbour)
        components.append(sorted(values))
    return components, component_by_node


def target_symmetries(target: Shape) -> tuple[tuple[str, CellMap], ...]:
    rows = [row for row, _ in target]
    cols = [col for _, col in target]
    row0, col0 = min(rows), min(cols)
    height = max(rows) - row0 + 1
    width = max(cols) - col0 + 1

    def lifted(local: CellMap) -> CellMap:
        return lambda row, col: tuple(
            value + offset
            for value, offset in zip(
                local(row - row0, col - col0),
                (row0, col0),
            )
        )  # type: ignore[return-value]

    candidates: list[tuple[str, CellMap]] = [
        ("id", lifted(lambda row, col: (row, col))),
        (
            "rot180",
            lifted(lambda row, col: (height - 1 - row, width - 1 - col)),
        ),
        ("flip_rows", lifted(lambda row, col: (height - 1 - row, col))),
        ("flip_cols", lifted(lambda row, col: (row, width - 1 - col))),
    ]
    if height == width:
        size = height
        candidates.extend(
            [
                ("rot90", lifted(lambda row, col: (col, size - 1 - row))),
                ("rot270", lifted(lambda row, col: (size - 1 - col, row))),
                ("diag", lifted(lambda row, col: (col, row))),
                (
                    "antidiag",
                    lifted(
                        lambda row, col: (
                            size - 1 - col,
                            size - 1 - row,
                        )
                    ),
                ),
            ]
        )
    accepted = []
    for name, action in candidates:
        image = frozenset(action(row, col) for row, col in target)
        if image == target and name not in {item[0] for item in accepted}:
            accepted.append((name, action))
    return tuple(accepted)


def transformed_node(node: Node, action: CellMap) -> Node:
    return tuple(
        frozenset(action(row, col) for row, col in placed)
        for placed in node
    )


def action_permutations(
    nodes: tuple[Node, ...],
    actions: tuple[tuple[str, CellMap], ...],
) -> tuple[tuple[int, ...], ...]:
    lookup = {node_key(node): index for index, node in enumerate(nodes)}
    permutations = []
    for name, action in actions:
        permutation = []
        for node in nodes:
            key = node_key(transformed_node(node, action))
            if key not in lookup:
                raise AssertionError(f"target action {name} does not close on fiber")
            permutation.append(lookup[key])
        if len(set(permutation)) != len(nodes):
            raise AssertionError(f"target action {name} is not a permutation")
        permutations.append(tuple(permutation))
    return tuple(permutations)


def orbit_ids(
    count: int,
    permutations: tuple[tuple[int, ...], ...],
) -> tuple[list[list[int]], list[int]]:
    seen = [-1] * count
    orbits: list[list[int]] = []
    for start in range(count):
        if seen[start] >= 0:
            continue
        values = sorted({permutation[start] for permutation in permutations})
        orbit_id = len(orbits)
        for value in values:
            if seen[value] not in (-1, orbit_id):
                raise AssertionError("target actions do not form disjoint orbits")
            seen[value] = orbit_id
        orbits.append(values)
    if any(value < 0 for value in seen):
        raise AssertionError("target action orbit did not cover every node")
    return orbits, seen


def minimax_barriers(
    energy: list[int],
    tilings: set[int],
    edges: list[set[int]],
) -> tuple[list[int | None], list[int | None], list[int | None]]:
    level: list[int | None] = [None] * len(energy)
    next_toward_tiling: list[int | None] = [None] * len(energy)
    queue: list[tuple[int, int]] = []
    for index in tilings:
        level[index] = 0
        heapq.heappush(queue, (0, index))
    while queue:
        current_level, current = heapq.heappop(queue)
        if level[current] != current_level:
            continue
        for neighbour in edges[current]:
            candidate = max(current_level, energy[neighbour])
            if level[neighbour] is None or candidate < level[neighbour]:
                level[neighbour] = candidate
                next_toward_tiling[neighbour] = current
                heapq.heappush(queue, (candidate, neighbour))
    beta = [
        None if level[index] is None else level[index] - energy[index]
        for index in range(len(energy))
    ]
    return level, beta, next_toward_tiling


def row_analysis(
    model: Model,
    quad: tuple[int, ...],
    nodes: tuple[Node, ...],
    actions: tuple[tuple[str, CellMap], ...],
) -> tuple[dict, dict]:
    edges = adjacency(nodes)
    components, component_by_node = graph_components(edges)
    energy = [
        len(model.target) - len(frozenset().union(*node))
        for node in nodes
    ]
    tilings = {index for index, value in enumerate(energy) if value == 0}
    tiled_components = {component_by_node[index] for index in tilings}
    trapped_components = {
        index
        for index in range(len(components))
        if index not in tiled_components
    }
    trapped_nodes = {
        node
        for index in trapped_components
        for node in components[index]
    }
    local_minima = {
        index
        for index, value in enumerate(energy)
        if value > 0
        and not any(energy[neighbour] < value for neighbour in edges[index])
    }
    level, beta, next_toward_tiling = minimax_barriers(
        energy,
        tilings,
        edges,
    )
    beta_values = [
        "INF" if value is None else value
        for value in beta
    ]
    if {index for index, value in enumerate(beta) if value is None} != trapped_nodes:
        raise AssertionError("infinite barriers must equal trapped nodes")

    permutations = action_permutations(nodes, actions)
    for permutation in permutations:
        for index, image in enumerate(permutation):
            if energy[index] != energy[image] or ((index in tilings) != (image in tilings)):
                raise AssertionError("target action does not preserve energy/tiling")
            if {permutation[value] for value in edges[index]} != edges[image]:
                raise AssertionError("target action does not preserve adjacency")
    node_orbits, node_orbit_by_node = orbit_ids(len(nodes), permutations)
    activated_orbit_ids = sorted(
        {
            node_orbit_by_node[index]
            for index, value in enumerate(beta)
            if value is not None and value > 0
        }
    )
    barrier_witnesses = []
    for orbit_id in activated_orbit_ids:
        representative = min(
            index
            for index in node_orbits[orbit_id]
            if beta[index] is not None and beta[index] > 0
        )
        path = [representative]
        while path[-1] not in tilings:
            next_node = next_toward_tiling[path[-1]]
            if next_node is None or next_node in path:
                raise AssertionError("invalid minimax predecessor certificate")
            if next_node not in edges[path[-1]]:
                raise AssertionError("minimax certificate uses a non-edge")
            path.append(next_node)
        if max(energy[index] for index in path) - energy[representative] != beta[representative]:
            raise AssertionError("minimax certificate has the wrong barrier")
        barrier_witnesses.append(
            {
                "node_orbit": orbit_id,
                "node_orbit_size": len(node_orbits[orbit_id]),
                "start_node_index": representative,
                "node_path": path,
                "phi_path": [energy[index] for index in path],
                "beta": beta[representative],
                "placement_path": [
                    [
                        [list(cell) for cell in sorted(placed)]
                        for placed in nodes[index]
                    ]
                    for index in path
                ],
            }
        )

    component_permutations = []
    for permutation in permutations:
        image = []
        for component in components:
            component_images = {
                component_by_node[permutation[node]]
                for node in component
            }
            if len(component_images) != 1:
                raise AssertionError("target action splits a graph component")
            image.append(next(iter(component_images)))
        component_permutations.append(tuple(image))
    component_orbits, _ = orbit_ids(
        len(components),
        tuple(component_permutations),
    )

    tiling_orbits = {
        node_orbit_by_node[index]
        for index in tilings
    }
    extra_orbits = {
        node_orbit_by_node[index]
        for index in range(len(nodes))
        if index not in tilings
    }
    trapped_component_orbits = sum(
        bool(set(orbit) & trapped_components)
        for orbit in component_orbits
    )
    profiles = Counter(
        (
            len(component),
            sum(index in tilings for index in component),
            min(energy[index] for index in component),
            max(energy[index] for index in component),
        )
        for component in components
    )
    profile_rows = [
        {
            "size": values[0],
            "tilings": values[1],
            "minimum_phi": values[2],
            "maximum_phi": values[3],
            "multiplicity": count,
        }
        for values, count in sorted(profiles.items())
    ]
    finite_beta = [value for value in beta if value is not None]
    local_minimum_classes = {
        "trapped": len(local_minima & trapped_nodes),
        "zero_barrier_plateau": sum(
            index in local_minima and beta[index] == 0
            for index in range(len(nodes))
        ),
        "positive_barrier": sum(
            index in local_minima
            and beta[index] is not None
            and beta[index] > 0
            for index in range(len(nodes))
        ),
    }
    if sum(local_minimum_classes.values()) != len(local_minima):
        raise AssertionError("local-minimum classes are not exhaustive")
    summary = {
        "piece_indices": list(quad),
        "piece_ids": [model.ids[index] for index in quad],
        "coarea_q": len(model.target) - max(
            len(model.pieces[index]) for index in quad
        ),
        "margin_nodes": len(nodes),
        "tiling_nodes": len(tilings),
        "extra_nodes": len(nodes) - len(tilings),
        "two_replacement_edges": sum(map(len, edges)) // 2,
        "components": len(components),
        "component_profiles": profile_rows,
        "trapped_components": len(trapped_components),
        "trapped_nodes": len(trapped_nodes),
        "nonzero_local_minima": len(local_minima),
        "local_minimum_classes": local_minimum_classes,
        "phi_distribution": distribution(energy),
        "beta_distribution": distribution(beta_values),
        "maximum_finite_beta": max(finite_beta, default=0),
        "activated_nodes": sum(
            value is not None and value > 0 for value in beta
        ),
        "activated_node_orbits": len(activated_orbit_ids),
        "barrier_witnesses": barrier_witnesses,
        "node_orbits": len(node_orbits),
        "component_orbits": len(component_orbits),
        "tiling_node_orbits": len(tiling_orbits),
        "extra_node_orbits": len(extra_orbits),
        "trapped_component_orbits": trapped_component_orbits,
    }
    internal = {
        "nodes": nodes,
        "edges": edges,
        "components": components,
        "component_by_node": component_by_node,
        "energy": energy,
        "beta": beta,
        "permutations": permutations,
    }
    return summary, internal


def integer_matrix(rows: list[list[int]]) -> DomainMatrix:
    if not rows or not rows[0]:
        raise ValueError("Smith input must be nonempty")
    return DomainMatrix(
        [[ZZ(value) for value in row] for row in rows],
        (len(rows), len(rows[0])),
        ZZ,
    )


def matrix_rows(matrix: DomainMatrix) -> list[list[int]]:
    return [[int(value) for value in row] for row in matrix.to_list()]


def matvec(rows: list[list[int]], vector: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(
        sum(value * coordinate for value, coordinate in zip(row, vector))
        for row in rows
    )


def pair_move_vectors(
    model: Model,
    quad: tuple[int, ...],
    active: tuple[tuple[Shape, ...], ...],
    column_index: tuple[dict[Shape, int], ...],
) -> tuple[tuple[int, ...], ...]:
    width = sum(len(values) for values in active)
    moves: set[tuple[int, ...]] = set()
    xrays = tuple(
        {placed: model.xray(placed) for placed in values}
        for values in active
    )
    for first, second in combinations(range(len(quad)), 2):
        buckets: dict[tuple[int, ...], list[tuple[Shape, Shape]]] = defaultdict(list)
        for left, right in product(active[first], active[second]):
            key = tuple(
                a + b for a, b in zip(xrays[first][left], xrays[second][right])
            )
            buckets[key].append((left, right))
        for pairs in buckets.values():
            seen = [False] * len(pairs)
            for start in range(len(pairs)):
                if seen[start]:
                    continue
                seen[start] = True
                queue = deque([start])
                while queue:
                    current = queue.popleft()
                    old_left, old_right = pairs[current]
                    for candidate, (new_left, new_right) in enumerate(pairs):
                        if (
                            seen[candidate]
                            or old_left == new_left
                            or old_right == new_right
                        ):
                            continue
                        seen[candidate] = True
                        queue.append(candidate)
                        vector = [0] * width
                        vector[column_index[first][new_left]] += 1
                        vector[column_index[second][new_right]] += 1
                        vector[column_index[first][old_left]] -= 1
                        vector[column_index[second][old_right]] -= 1
                        values = tuple(vector)
                        opposite = tuple(-value for value in values)
                        moves.add(min(values, opposite))
    return tuple(sorted(moves))


def participating_quotient(
    model: Model,
    quad: tuple[int, ...],
    internal: dict,
) -> dict:
    started = time.perf_counter()
    nodes: tuple[Node, ...] = internal["nodes"]
    active = tuple(
        tuple(
            sorted(
                {node[position] for node in nodes},
                key=shape_key,
            )
        )
        for position in range(len(quad))
    )
    offsets = []
    cursor = 0
    for values in active:
        offsets.append(cursor)
        cursor += len(values)
    columns = cursor
    column_index = tuple(
        {
            placed: offsets[position] + local
            for local, placed in enumerate(values)
        }
        for position, values in enumerate(active)
    )

    rows = [[0] * columns for _ in range(len(quad) + len(model.target_xray))]
    for position, values in enumerate(active):
        for placed in values:
            column = column_index[position][placed]
            rows[position][column] = 1
            for index, value in enumerate(model.xray(placed)):
                rows[len(quad) + index][column] = value
    ambient = integer_matrix(rows)
    diagonal, left, right = smith_normal_decomp(ambient)
    if left * ambient * right != diagonal:
        raise AssertionError("ambient Smith decomposition failed")
    diagonal_rows = matrix_rows(diagonal)
    ambient_rank = sum(
        diagonal_rows[index][index] != 0
        for index in range(min(diagonal.shape))
    )
    right_inverse, denominator = right.inv_den()
    if abs(int(denominator)) != 1:
        raise AssertionError("ambient Smith transform is not unimodular")
    inverse_rows = [
        [value // int(denominator) for value in row]
        for row in matrix_rows(right_inverse)
    ]
    kernel_rank = columns - ambient_rank

    def sparse_node(node: Node) -> tuple[int, ...]:
        vector = [0] * columns
        for position, placed in enumerate(node):
            vector[column_index[position][placed]] = 1
        return tuple(vector)

    def kernel_coordinates(vector: tuple[int, ...]) -> tuple[int, ...]:
        transformed = matvec(inverse_rows, vector)
        if any(transformed[:ambient_rank]):
            raise AssertionError("purported kernel vector is outside kernel")
        return transformed[ambient_rank:]

    moves = pair_move_vectors(model, quad, active, column_index)
    move_coordinates = tuple(
        kernel_coordinates(move)
        for move in moves
    )
    move_coordinates = tuple(
        sorted(set(move_coordinates))
    )

    if kernel_rank == 0:
        move_rank = 0
        quotient_left_rows: list[list[int]] = []
        invariant_diagonal: list[int] = []
    elif move_coordinates:
        move_rows = [
            [move[index] for move in move_coordinates]
            for index in range(kernel_rank)
        ]
        move_matrix = integer_matrix(move_rows)
        move_diagonal, move_left, move_right = smith_normal_decomp(move_matrix)
        if move_left * move_matrix * move_right != move_diagonal:
            raise AssertionError("move Smith decomposition failed")
        move_diagonal_rows = matrix_rows(move_diagonal)
        move_rank = sum(
            move_diagonal_rows[index][index] != 0
            for index in range(min(move_diagonal.shape))
        )
        invariant_diagonal = [
            abs(move_diagonal_rows[index][index])
            for index in range(move_rank)
        ]
        quotient_left_rows = matrix_rows(move_left)
    else:
        move_rank = 0
        invariant_diagonal = []
        quotient_left_rows = [
            [int(row == col) for col in range(kernel_rank)]
            for row in range(kernel_rank)
        ]

    def quotient_class(coordinates: tuple[int, ...]) -> tuple[tuple[int, ...], tuple[int, ...]]:
        if kernel_rank == 0:
            return (), ()
        transformed = matvec(quotient_left_rows, coordinates)
        torsion = tuple(
            transformed[index] % invariant_diagonal[index]
            for index in range(move_rank)
        )
        free = transformed[move_rank:]
        return torsion, free

    base = sparse_node(nodes[0])
    classes = []
    for node in nodes:
        vector = tuple(
            value - reference
            for value, reference in zip(sparse_node(node), base)
        )
        classes.append(quotient_class(kernel_coordinates(vector)))

    components: list[list[int]] = internal["components"]
    energy: list[int] = internal["energy"]
    component_classes = []
    for component in components:
        values = {classes[index] for index in component}
        if len(values) != 1:
            raise AssertionError("graph component crosses a quotient coset")
        component_classes.append(next(iter(values)))
    components_per_coset = Counter(component_classes)
    split_cosets = {
        value: count
        for value, count in components_per_coset.items()
        if count > 1
    }
    components_by_coset: dict[tuple, list[int]] = defaultdict(list)
    for component_id, value in enumerate(component_classes):
        components_by_coset[value].append(component_id)
    split_witnesses = []
    mixed_tiled_trapped = 0
    for value, component_ids in sorted(
        components_by_coset.items(),
        key=lambda item: repr(item[0]),
    ):
        if len(component_ids) <= 1:
            continue
        tiled_flags = [
            any(energy[node] == 0 for node in components[component_id])
            for component_id in component_ids
        ]
        mixed = any(tiled_flags) and not all(tiled_flags)
        mixed_tiled_trapped += mixed
        representatives = []
        for component_id, tiled in zip(component_ids, tiled_flags):
            component = components[component_id]
            representative = min(
                (
                    node
                    for node in component
                    if (energy[node] == 0) == tiled
                ),
                default=min(component),
            )
            representatives.append(
                {
                    "component": component_id,
                    "node": representative,
                    "phi": energy[representative],
                    "component_contains_tiling": tiled,
                }
            )
        split_witnesses.append(
            {
                "components_in_coset": len(component_ids),
                "mixes_tiled_and_trapped_components": mixed,
                "representatives": representatives,
            }
        )

    well_defined = True
    for permutation in internal["permutations"]:
        images: dict[tuple, set[tuple]] = defaultdict(set)
        for index, value in enumerate(classes):
            images[value].add(classes[permutation[index]])
        well_defined &= all(len(values) == 1 for values in images.values())

    torsion_factors = [
        value for value in invariant_diagonal if value > 1
    ]
    return {
        "piece_indices": list(quad),
        "piece_ids": [model.ids[index] for index in quad],
        "fiber_nodes": len(nodes),
        "participating_placements_by_piece": [len(values) for values in active],
        "participating_columns": columns,
        "constraint_rows": len(rows),
        "ambient_kernel_rank": kernel_rank,
        "algebraic_two_piece_generators": len(moves),
        "move_lattice_rank": move_rank,
        "quotient_free_rank": kernel_rank - move_rank,
        "quotient_torsion_factors": torsion_factors,
        "quotient_cosets_hit_by_nodes": len(set(classes)),
        "graph_components": len(components),
        "split_hit_cosets": len(split_cosets),
        "mixed_tiled_trapped_hit_cosets": mixed_tiled_trapped,
        "split_coset_witnesses": split_witnesses,
        "maximum_components_in_one_hit_coset": max(
            components_per_coset.values(),
            default=0,
        ),
        "components_per_hit_coset_distribution": distribution(
            components_per_coset.values()
        ),
        "component_coset_homogeneous": True,
        "target_action_well_defined_on_hit_cosets": well_defined,
        "runtime_seconds": round(time.perf_counter() - started, 6),
    }


def select_quotient_rows(
    model_name: str,
    rows: list[dict],
) -> tuple[tuple[int, ...], ...]:
    selected: set[tuple[int, ...]] = set()
    if model_name == "C32":
        maximum = max(row["margin_nodes"] for row in rows)
        selected.add(
            min(
                tuple(row["piece_indices"])
                for row in rows
                if row["margin_nodes"] == maximum
            )
        )
    elif model_name == "C46":
        selected.update(
            tuple(row["piece_indices"])
            for row in rows
            if row["extra_nodes"] > 0
        )
    elif model_name == "P49-base":
        available = {tuple(row["piece_indices"]) for row in rows}
        for quad in ((0, 1, 3, 14), (4, 9, 10, 11)):
            if quad not in available:
                raise AssertionError(f"missing frozen P49 witness {quad}")
            selected.add(quad)
    else:
        maximum_beta = max(row["maximum_finite_beta"] for row in rows)
        selected.add(
            min(
                tuple(row["piece_indices"])
                for row in rows
                if row["maximum_finite_beta"] == maximum_beta
            )
        )
        live_trapped = [
            tuple(row["piece_indices"])
            for row in rows
            if row["tiling_nodes"] > 0 and row["trapped_components"] > 0
        ]
        if live_trapped:
            selected.add(min(live_trapped))
        support_failures = [
            tuple(row["piece_indices"])
            for row in rows
            if row["tiling_nodes"] == 0
        ]
        if support_failures:
            selected.add(min(support_failures))
    return tuple(sorted(selected))


def load_panel() -> tuple[Model, ...]:
    c32, c46, p49 = load_models()
    return (
        c32,
        c46,
        p49,
        model_from_locked("p21_locked.json"),
        model_from_locked("p26_locked.json"),
    )


def analyse_model(model: Model) -> tuple[dict, dict[tuple[int, ...], dict]]:
    started = time.perf_counter()
    actions = target_symmetries(model.target)
    rows = []
    internals: dict[tuple[int, ...], dict] = {}
    totals = Counter()
    phi = Counter()
    beta = Counter()
    maximum_finite_beta = 0
    for quad in model.quaternes():
        nodes = model.fiber(quad)
        if not nodes:
            continue
        summary, internal = row_analysis(model, quad, nodes, actions)
        rows.append(summary)
        internals[quad] = internal
        for field in (
            "margin_nodes",
            "tiling_nodes",
            "extra_nodes",
            "two_replacement_edges",
            "components",
            "trapped_components",
            "trapped_nodes",
            "nonzero_local_minima",
            "activated_node_orbits",
            "activated_nodes",
            "node_orbits",
            "component_orbits",
            "tiling_node_orbits",
            "extra_node_orbits",
            "trapped_component_orbits",
        ):
            totals[field] += summary[field]
        totals["margin_feasible_rows"] += 1
        totals["tiling_rows"] += summary["tiling_nodes"] > 0
        totals["activated_rows"] += summary["activated_nodes"] > 0
        for field, value in summary["local_minimum_classes"].items():
            totals[f"local_minima_{field}"] += value
        for value, count in summary["phi_distribution"].items():
            phi[value] += count
        for value, count in summary["beta_distribution"].items():
            beta[value] += count
        maximum_finite_beta = max(
            maximum_finite_beta,
            summary["maximum_finite_beta"],
        )

    rows.sort(key=lambda row: tuple(row["piece_indices"]))
    expected = EXPECTED[model.name]
    observed = (
        totals["margin_nodes"],
        totals["tiling_nodes"],
        totals["extra_nodes"],
    )
    if observed != expected:
        raise AssertionError(
            f"{model.name}: established totals changed {observed}!={expected}"
        )
    output = {
        "library": model.name,
        "input_path": str(model.source.relative_to(PROJECT)).replace("\\", "/"),
        "input_sha256": sha256(model.source),
        "target_cells": len(model.target),
        "area_compatible_rows": len(model.quaternes()),
        "target_automorphisms": [name for name, _ in actions],
        "target_automorphism_order": len(actions),
        **dict(totals),
        "phi_distribution": dict(sorted(phi.items())),
        "beta_distribution": dict(sorted(beta.items())),
        "maximum_finite_beta": maximum_finite_beta,
        "rows": rows,
        "runtime_seconds": round(time.perf_counter() - started, 6),
    }
    return output, internals


def validate_result(result: dict) -> None:
    if result["status"] != "PASS":
        raise AssertionError("result status must be PASS")
    libraries = {row["library"]: row for row in result["libraries"]}
    if set(libraries) != set(EXPECTED):
        raise AssertionError("finite panel is incomplete")
    for name, expected in EXPECTED.items():
        row = libraries[name]
        observed = (
            row["margin_nodes"],
            row["tiling_nodes"],
            row["extra_nodes"],
        )
        if observed != expected:
            raise AssertionError(f"{name}: aggregate drift")
        if row["beta_distribution"].get("INF", 0) != row["trapped_nodes"]:
            raise AssertionError(f"{name}: beta=INF mismatch")
    for quotient in result["quotient_witnesses"]:
        if not quotient["component_coset_homogeneous"]:
            raise AssertionError("component crossed quotient cosets")
        if not quotient["target_action_well_defined_on_hit_cosets"]:
            raise AssertionError("target action failed on quotient hit set")


def main() -> int:
    started = time.perf_counter()
    libraries = []
    model_internals: dict[str, dict[tuple[int, ...], dict]] = {}
    models = load_panel()
    for model in models:
        summary, internals = analyse_model(model)
        libraries.append(summary)
        model_internals[model.name] = internals
        print(
            f"{model.name:9s}: "
            f"{summary['margin_nodes']}="
            f"{summary['tiling_nodes']}+{summary['extra_nodes']}; "
            f"beta+={summary['activated_nodes']}; "
            f"betaINF={summary['trapped_nodes']}; "
            f"|Aut(T)|={summary['target_automorphism_order']}"
        )

    quotient_witnesses = []
    for model, library in zip(models, libraries):
        selected = select_quotient_rows(model.name, library["rows"])
        lookup = {
            tuple(row["piece_indices"]): row
            for row in library["rows"]
        }
        for quad in selected:
            quotient = participating_quotient(
                model,
                quad,
                model_internals[model.name][quad],
            )
            quotient["selection_metrics"] = {
                "tiling_nodes": lookup[quad]["tiling_nodes"],
                "extra_nodes": lookup[quad]["extra_nodes"],
                "trapped_components": lookup[quad]["trapped_components"],
                "maximum_finite_beta": lookup[quad]["maximum_finite_beta"],
            }
            quotient["library"] = model.name
            quotient_witnesses.append(quotient)
            print(
                f"  quotient {model.name} {quad}: "
                f"K={quotient['ambient_kernel_rank']} "
                f"M2={quotient['move_lattice_rank']} "
                f"Qfree={quotient['quotient_free_rank']} "
                f"cosets/components="
                f"{quotient['quotient_cosets_hit_by_nodes']}/"
                f"{quotient['graph_components']} "
                f"splits={quotient['split_hit_cosets']}"
            )

    result = {
        "schema_version": "p42.placement_quotient.v1",
        "status": "PASS",
        "scope": {
            "complete_finite_panel": [
                "C32",
                "C46",
                "P49-base",
                "P21",
                "P26",
            ],
            "lattice": "participating placements only",
            "move": "exactly two named placements change",
            "nonclaim": "finite evidence, not a universal Markov basis",
        },
        "preregistration": {
            "path": str(PREREGISTRATION.relative_to(PROJECT)).replace("\\", "/"),
            "sha256": sha256(PREREGISTRATION),
        },
        "environment": {
            "python": platform.python_version(),
            "platform": platform.platform(),
        },
        "libraries": libraries,
        "quotient_witnesses": quotient_witnesses,
        "runtime_seconds": round(time.perf_counter() - started, 6),
    }
    validate_result(result)
    OUTPUT.write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        f"PASS: {sum(row['margin_nodes'] for row in libraries)} nodes; "
        f"{len(quotient_witnesses)} exact quotient witnesses; "
        f"{result['runtime_seconds']:.3f}s"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
